// <auto-generated />
namespace AdbrainReddit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddedWillCascadeOnDeletetrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedWillCascadeOnDeletetrue));
        
        string IMigrationMetadata.Id
        {
            get { return "201412291125292_Added WillCascadeOnDelete(true)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
